# Generated by Django 4.0.1 on 2022-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='timestamp',
            field=models.DateField(db_column='timestamp', verbose_name='创建日期'),
        ),
    ]
