# Generated by Django 4.0.1 on 2022-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0002_alter_configuration_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(choices=[('1', 'HTTP服务'), ('2', 'DNS服务'), ('3', 'JNDI服务'), ('4', 'HTTPS服务'), ('5', 'TCP监听')], max_length=2, unique=True, verbose_name='配置名称')),
                ('port', models.IntegerField(db_column='port', verbose_name='端口')),
                ('ipaddress', models.GenericIPAddressField(db_column='ipaddress', default='127.0.0.1', verbose_name='系统地址')),
                ('domain', models.CharField(blank=True, db_column='domain', default='apollo.local', max_length=256, null=True, verbose_name='系统域名')),
            ],
            options={
                'verbose_name': '服务配置',
                'verbose_name_plural': '服务配置',
            },
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='timestamp',
        ),
    ]
