# Generated by Django 4.0.1 on 2022-03-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0003_services_remove_configuration_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='services',
            name='ipaddress',
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(choices=[('1', 'HTTP服务'), ('2', 'DNS服务'), ('3', 'JNDI服务'), ('5', 'TCP监听')], max_length=2, unique=True, verbose_name='配置名称'),
        ),
    ]
