# Generated by Django 4.0.1 on 2022-03-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0004_remove_services_domain_remove_services_ipaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='ip_address',
            field=models.GenericIPAddressField(db_column='ip_address', default='127.0.0.1', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(choices=[('1', 'HTTP服务'), ('2', 'DNS服务'), ('3', 'JNDI服务'), ('4', 'TCP监听')], max_length=2, unique=True, verbose_name='配置名称'),
        ),
    ]
