# Generated by Django 4.0.1 on 2022-03-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0007_alter_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(choices=[('1', 'HTTP日志'), ('2', 'DNS日志')], max_length=2, unique=True, verbose_name='配置名称')),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address', verbose_name='源地址')),
                ('message', models.CharField(choices=[('1', 'HTTP日志'), ('2', 'DNS日志')], max_length=2, unique=True, verbose_name='配置名称')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='记录时间')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='state',
            field=models.BooleanField(db_column='state', default=False, editable=False, verbose_name='服务开启'),
        ),
    ]
