# Generated by Django 4.0.1 on 2022-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0008_serviceslog_alter_services_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslog',
            name='ip_address',
            field=models.GenericIPAddressField(db_column='ip_address', editable=False, verbose_name='源地址'),
        ),
        migrations.AlterField(
            model_name='serviceslog',
            name='message',
            field=models.CharField(choices=[('1', 'HTTP日志'), ('2', 'DNS日志')], editable=False, max_length=2, unique=True, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='serviceslog',
            name='name',
            field=models.CharField(choices=[('1', 'HTTP日志'), ('2', 'DNS日志')], editable=False, max_length=2, unique=True, verbose_name='配置名称'),
        ),
    ]
