# Generated by Django 4.0.1 on 2022-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0009_alter_serviceslog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(choices=[('1', 'HTTP服务'), ('2', 'TCP监听')], max_length=2, unique=True, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='serviceslog',
            name='message',
            field=models.CharField(editable=False, max_length=256, verbose_name='访问记录'),
        ),
        migrations.AlterField(
            model_name='serviceslog',
            name='name',
            field=models.CharField(choices=[('1', 'HTTP日志')], editable=False, max_length=2, unique=True, verbose_name='配置名称'),
        ),
    ]
