# Generated by Django 4.0.1 on 2022-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0011_alter_serviceslog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslog',
            name='name',
            field=models.CharField(default='HTTP日志', editable=False, max_length=20, verbose_name='日志类型'),
        ),
    ]
