# Generated by Django 4.0.1 on 2022-03-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0012_alter_serviceslog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslog',
            name='method',
            field=models.CharField(default='GET', editable=False, max_length=20, verbose_name='请求类型'),
        ),
        migrations.AddField(
            model_name='serviceslog',
            name='status',
            field=models.CharField(default='200', editable=False, max_length=20, verbose_name='响应码'),
        ),
        migrations.AlterField(
            model_name='serviceslog',
            name='name',
            field=models.CharField(editable=False, max_length=20, verbose_name='日志类型'),
        ),
    ]
