# Generated by Django 4.0.1 on 2022-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0014_alter_services_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(choices=[('1', 'HTTP服务'), ('2', 'DNS服务')], max_length=2, unique=True, verbose_name='配置名称'),
        ),
    ]
