# Generated by Django 4.2.8 on 2024-09-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0015_alter_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='员工姓名')),
                ('worker_id', models.CharField(db_column='worker_id', max_length=10, verbose_name='员工工号')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], db_column='gender', max_length=2, verbose_name='性别')),
                ('department', models.CharField(db_column='department', max_length=20, verbose_name='所在部门')),
            ],
            options={
                'verbose_name': '员工配置',
                'verbose_name_plural': '员工配置',
            },
        ),
        migrations.CreateModel(
            name='DutyTable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('date', models.DateField(auto_now=True, db_column='date', verbose_name='值班时间')),
                ('weekday', models.CharField(choices=[('0', '周一'), ('1', '周二'), ('2', '周三'), ('3', '周四'), ('4', '周五'), ('5', '周六'), ('6', '周日')], default='0', max_length=2, verbose_name='星期')),
                ('overtime_type', models.CharField(choices=[('0', '周末值班'), ('1', '元旦值班'), ('3', '清明值班'), ('4', '五一值班'), ('5', '端午值班'), ('6', '中秋值班'), ('7', '国庆值班'), ('8', '护网值班')], default='0', max_length=2, verbose_name='值班类型')),
                ('work_type', models.CharField(choices=[('0', '现场'), ('1', '远程')], default='0', max_length=2, verbose_name='值班方式')),
                ('worker', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.worker', verbose_name='值班人')),
            ],
            options={
                'verbose_name': '值班表',
                'verbose_name_plural': '值班表',
            },
        ),
    ]
