# Generated by Django 4.0.1 on 2025-01-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assets', '0004_alter_assetlist_middle_ware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleiPoCRegister',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('exploit_name', models.CharField(db_column='exploit_name', max_length=32, verbose_name='负载名称')),
                ('category', models.CharField(choices=[('1', 'WEB漏洞'), ('2', '系统漏洞')], max_length=2, verbose_name='漏洞类型')),
                ('filename', models.CharField(db_column='filename', default='', max_length=100, verbose_name='文件名称')),
                ('yamlcode', models.TextField(db_column='yamlcode', null=True, verbose_name='负载代码(仅支持yaml)')),
                ('description', models.TextField(db_column='description', verbose_name='负载描述')),
                ('debug_info', models.TextField(blank=True, db_column='debug_info', default='', null=True, verbose_name='调试信息')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assets.assetlist', verbose_name='调试目标')),
            ],
            options={
                'verbose_name': '负载管理',
                'verbose_name_plural': '负载管理',
            },
        ),
        migrations.CreateModel(
            name='NucleiScanResult',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('task_id', models.IntegerField(db_column='task_id', verbose_name='对应工单序号')),
                ('task_name', models.CharField(db_column='task_name', max_length=32, verbose_name='工单名称')),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address', verbose_name='目标地址')),
                ('port', models.IntegerField(db_column='port', null=True, verbose_name='目标端口')),
                ('result_flag', models.BooleanField(db_column='result_flag', verbose_name='测试结果')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '扫描结果',
                'verbose_name_plural': '扫描结果',
            },
        ),
        migrations.CreateModel(
            name='NucleiScanTasks',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='任务名称')),
                ('targets', models.TextField(blank=True, db_column='targets', null=True, verbose_name='目标群')),
                ('notice', models.BooleanField(db_column='notice', default=False, verbose_name='是否钉钉通知')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间')),
                ('exploit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NucleiScan.nucleipocregister', verbose_name='漏洞负载选择')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assets.assetlist', verbose_name='目标选择')),
            ],
            options={
                'verbose_name': '任务项',
                'verbose_name_plural': '任务项',
            },
        ),
    ]
