# Generated by Django 4.0.1 on 2022-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address', verbose_name='IP地址')),
                ('top_level_domain', models.TextField(blank=True, db_column='top_level_domain', null=True, verbose_name='主域名')),
                ('subdomain', models.TextField(blank=True, db_column='subdomain', null=True, verbose_name='子域名')),
                ('cname', models.TextField(blank=True, db_column='cname', null=True, verbose_name='别名')),
                ('system', models.TextField(blank=True, db_column='system', null=True, verbose_name='操作系统')),
                ('port', models.IntegerField(blank=True, db_column='port', null=True, verbose_name='端口')),
                ('state', models.CharField(blank=True, choices=[('0', '关闭'), ('1', '开放'), ('2', '阻断')], max_length=2, null=True, verbose_name='端口状态')),
                ('protocol', models.TextField(blank=True, db_column='protocol', null=True, verbose_name='协议')),
                ('service', models.TextField(blank=True, db_column='service', null=True, verbose_name='服务')),
                ('software', models.TextField(blank=True, db_column='software', null=True, verbose_name='组件')),
                ('version', models.TextField(blank=True, db_column='version', null=True, verbose_name='版本')),
                ('website_title', models.TextField(blank=True, db_column='website_title', null=True, verbose_name='站点标题')),
                ('middle_ware', models.TextField(blank=True, db_column='middle_ware', null=True, verbose_name='组件/框架')),
                ('timestamp', models.DateField(db_column='timestamp', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '资产信息',
                'verbose_name_plural': '资产信息',
            },
        ),
        migrations.CreateModel(
            name='AssetTask',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.TextField(db_column='name', verbose_name='任务名称')),
                ('top_level_domain', models.TextField(db_column='top_level_domain', verbose_name='主域名')),
                ('port_scan_type', models.CharField(choices=[('0', '关键端口'), ('1', '常用端口'), ('2', '全端口')], max_length=2, verbose_name='端口自类型')),
                ('timestamp', models.DateField(db_column='timestamp', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
            },
        ),
    ]
