# Generated by Django 4.0.1 on 2022-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='cname',
            field=models.CharField(blank=True, db_column='cname', max_length=256, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='middle_ware',
            field=models.CharField(blank=True, db_column='middle_ware', max_length=50, null=True, verbose_name='组件/框架'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='protocol',
            field=models.CharField(blank=True, db_column='protocol', max_length=50, null=True, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='service',
            field=models.CharField(blank=True, db_column='service', max_length=50, null=True, verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='software',
            field=models.CharField(blank=True, db_column='software', max_length=50, null=True, verbose_name='组件'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='subdomain',
            field=models.CharField(blank=True, db_column='subdomain', max_length=256, null=True, verbose_name='子域名'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='system',
            field=models.CharField(blank=True, db_column='system', max_length=50, null=True, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='top_level_domain',
            field=models.CharField(blank=True, db_column='top_level_domain', max_length=256, null=True, verbose_name='主域名'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='version',
            field=models.CharField(blank=True, db_column='version', max_length=50, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='assetlist',
            name='website_title',
            field=models.CharField(blank=True, db_column='website_title', max_length=256, null=True, verbose_name='站点标题'),
        ),
        migrations.AlterField(
            model_name='assettask',
            name='name',
            field=models.CharField(db_column='name', max_length=50, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='assettask',
            name='top_level_domain',
            field=models.CharField(db_column='top_level_domain', max_length=256, verbose_name='主域名'),
        ),
    ]
