# Generated by Django 4.0.1 on 2022-03-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_alter_assetlist_cname_alter_assetlist_middle_ware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='assettask',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间'),
        ),
    ]
