# Generated by Django 4.0.1 on 2022-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0003_alter_assetlist_timestamp_alter_assettask_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='middle_ware',
            field=models.CharField(blank=True, db_column='middle_ware', max_length=512, null=True, verbose_name='组件/框架'),
        ),
        migrations.AlterField(
            model_name='assettask',
            name='port_scan_type',
            field=models.CharField(choices=[('0', '关键端口'), ('1', '常用端口'), ('2', '全端口')], default='0', max_length=2, verbose_name='端口自类型'),
        ),
    ]
