# Generated by Django 4.0.1 on 2022-03-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GithubScan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GithubResult',
            new_name='GithubScanResult',
        ),
    ]
