# Generated by Django 4.0.1 on 2022-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubScan', '0002_rename_githubresult_githubscanresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubscanresult',
            name='timestamp',
            field=models.DateField(db_column='timestamp', verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='githubscantask',
            name='timestamp',
            field=models.DateField(db_column='timestamp', verbose_name='创建日期'),
        ),
    ]
