# Generated by Django 4.0.1 on 2022-03-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GithubScan', '0004_remove_githubscanresult_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubscanresult',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='githubscantask',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建日期'),
        ),
    ]
