# Generated by Django 4.0.1 on 2022-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathScanResult',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='任务名称')),
                ('url', models.CharField(blank=True, db_column='url', max_length=256, null=True, verbose_name='链接')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务管理',
                'verbose_name_plural': '任务管理',
            },
        ),
        migrations.CreateModel(
            name='PathScanTask',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='任务名称')),
                ('target', models.CharField(db_column='target', max_length=256, verbose_name='目标URL')),
                ('state', models.BooleanField(db_column='state', verbose_name='完成与否')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '任务管理',
                'verbose_name_plural': '任务管理',
            },
        ),
    ]
