# Generated by Django 4.0.1 on 2022-03-09 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assets', '0002_alter_assetlist_cname_alter_assetlist_middle_ware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BruteRegister',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('exploit_name', models.CharField(db_column='exploit_name', max_length=32, verbose_name='负载名称')),
                ('category', models.CharField(choices=[('1', 'WEB暴破'), ('2', '系统暴破')], max_length=2, verbose_name='漏洞类型')),
                ('file_object', models.FileField(null=True, upload_to='BruteScan/ExploitFiles/', verbose_name='负载上传')),
                ('description', models.TextField(db_column='description', verbose_name='漏洞描述')),
                ('timestamp', models.DateField(db_column='timestamp', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '负载管理',
                'verbose_name_plural': '负载管理',
            },
        ),
        migrations.CreateModel(
            name='BruteResult',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('task_id', models.IntegerField(db_column='task_id', verbose_name='对应工单序号')),
                ('task_name', models.CharField(db_column='task_name', max_length=32, verbose_name='工单名称')),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address', verbose_name='目标地址')),
                ('port', models.IntegerField(db_column='port', null=True, verbose_name='目标端口')),
                ('result_flag', models.BooleanField(db_column='result_flag', verbose_name='测试结果')),
                ('timestamp', models.DateField(db_column='timestamp', verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '工单结果',
                'verbose_name_plural': '工单结果',
            },
        ),
        migrations.CreateModel(
            name='BruteTasks',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='任务名称')),
                ('targets', models.TextField(db_column='targets', verbose_name='目标群')),
                ('timestamp', models.DateField(db_column='timestamp', default=django.utils.timezone.now, verbose_name='创建日期')),
                ('exploit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BruteScan.bruteregister', verbose_name='暴破负载选择')),
                ('target', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assets.assetlist', verbose_name='目标选择')),
            ],
            options={
                'verbose_name': '任务项',
                'verbose_name_plural': '任务项',
            },
        ),
    ]
