# Generated by Django 4.0.1 on 2022-03-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_alter_assetlist_cname_alter_assetlist_middle_ware_and_more'),
        ('BruteScan', '0002_remove_bruteresult_result_flag_bruteresult_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruteregister',
            name='category',
            field=models.CharField(choices=[('1', 'WEB暴破'), ('2', '系统暴破')], max_length=2, verbose_name='负载类型'),
        ),
        migrations.AlterField(
            model_name='bruteregister',
            name='description',
            field=models.TextField(db_column='description', verbose_name='负载描述'),
        ),
        migrations.AlterField(
            model_name='brutetasks',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assets.assetlist', verbose_name='目标选择'),
        ),
        migrations.AlterField(
            model_name='brutetasks',
            name='targets',
            field=models.TextField(blank=True, db_column='targets', null=True, verbose_name='目标群'),
        ),
    ]
