# Generated by Django 4.0.1 on 2022-03-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BruteScan', '0003_alter_bruteregister_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruteregister',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bruteresult',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='brutetasks',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp', verbose_name='创建时间'),
        ),
    ]
