# Generated by Django 4.0.1 on 2022-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BruteScan', '0004_alter_bruteregister_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bruteregister',
            name='file_object',
        ),
        migrations.AddField(
            model_name='bruteregister',
            name='code',
            field=models.TextField(db_column='code', null=True, verbose_name='负载代码'),
        ),
        migrations.AddField(
            model_name='bruteregister',
            name='debug_info',
            field=models.TextField(db_column='debug_info', default='', verbose_name='调试信息'),
        ),
    ]
