# Generated by Django 4.0.1 on 2022-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BruteScan', '0005_remove_bruteregister_file_object_bruteregister_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruteregister',
            name='function_name',
            field=models.CharField(db_column='function_name', default='', max_length=100, verbose_name='函数名称'),
        ),
        migrations.AlterField(
            model_name='bruteregister',
            name='debug_info',
            field=models.TextField(blank=True, db_column='debug_info', default='', null=True, verbose_name='调试信息'),
        ),
    ]
