# Generated by Django 4.0.1 on 2022-03-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0003_alter_assetlist_timestamp_alter_assettask_timestamp'),
        ('BruteScan', '0006_bruteregister_function_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruteregister',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assets.assetlist', verbose_name='调试目标'),
        ),
    ]
