# Generated by Django 4.0.1 on 2022-03-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BruteScan', '0007_bruteregister_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='brutetasks',
            name='notice',
            field=models.BooleanField(db_column='notice', default=False, verbose_name='是否钉钉通知'),
        ),
    ]
